//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Preguntas_Respuestas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREGUNTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PREGUNTAS()
        {
            this.RESPUESTAS = new HashSet<RESPUESTAS>();
        }
    
        public int ID_PREGUN { get; set; }
        public string PREGUNTA { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESPUESTAS> RESPUESTAS { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
