//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Preguntas_Respuestas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Datos : DbContext
    {
        public Datos()
            : base("name=Datos")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ESTADO> ESTADO { get; set; }
        public virtual DbSet<PREGUNTAS> PREGUNTAS { get; set; }
        public virtual DbSet<RESPUESTAS> RESPUESTAS { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    
        public virtual int CREARPREGUNTA(string pREGUNTA, Nullable<int> iD_USUARIO)
        {
            var pREGUNTAParameter = pREGUNTA != null ?
                new ObjectParameter("PREGUNTA", pREGUNTA) :
                new ObjectParameter("PREGUNTA", typeof(string));
    
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREARPREGUNTA", pREGUNTAParameter, iD_USUARIOParameter);
        }
    
        public virtual int CREARRESPUESTA(string rESPUESTA, Nullable<int> iD_USUARIO, Nullable<int> iD_PREGUNTA)
        {
            var rESPUESTAParameter = rESPUESTA != null ?
                new ObjectParameter("RESPUESTA", rESPUESTA) :
                new ObjectParameter("RESPUESTA", typeof(string));
    
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            var iD_PREGUNTAParameter = iD_PREGUNTA.HasValue ?
                new ObjectParameter("ID_PREGUNTA", iD_PREGUNTA) :
                new ObjectParameter("ID_PREGUNTA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREARRESPUESTA", rESPUESTAParameter, iD_USUARIOParameter, iD_PREGUNTAParameter);
        }
    
        public virtual int CREARUSUARIO(string nOMBRE, string uSUARIO, string cONTRASEÑA)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var cONTRASEÑAParameter = cONTRASEÑA != null ?
                new ObjectParameter("CONTRASEÑA", cONTRASEÑA) :
                new ObjectParameter("CONTRASEÑA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREARUSUARIO", nOMBREParameter, uSUARIOParameter, cONTRASEÑAParameter);
        }
    
        public virtual int DESACTIVARPREGUNTA(Nullable<int> iD_PREGUNTA, Nullable<int> iD_ESTADO)
        {
            var iD_PREGUNTAParameter = iD_PREGUNTA.HasValue ?
                new ObjectParameter("ID_PREGUNTA", iD_PREGUNTA) :
                new ObjectParameter("ID_PREGUNTA", typeof(int));
    
            var iD_ESTADOParameter = iD_ESTADO.HasValue ?
                new ObjectParameter("ID_ESTADO", iD_ESTADO) :
                new ObjectParameter("ID_ESTADO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DESACTIVARPREGUNTA", iD_PREGUNTAParameter, iD_ESTADOParameter);
        }
    
        public virtual ObjectResult<LISTARPREGUNTAS_Result> LISTARPREGUNTAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LISTARPREGUNTAS_Result>("LISTARPREGUNTAS");
        }
    
        public virtual ObjectResult<LISTARRESPUESTAS_Result> LISTARRESPUESTAS(Nullable<int> iD_PREGUNTA)
        {
            var iD_PREGUNTAParameter = iD_PREGUNTA.HasValue ?
                new ObjectParameter("ID_PREGUNTA", iD_PREGUNTA) :
                new ObjectParameter("ID_PREGUNTA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LISTARRESPUESTAS_Result>("LISTARRESPUESTAS", iD_PREGUNTAParameter);
        }
    
        public virtual ObjectResult<LOGINUSUARIO_Result> LOGINUSUARIO(string uSUARIO, string cONTRASEÑA)
        {
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var cONTRASEÑAParameter = cONTRASEÑA != null ?
                new ObjectParameter("CONTRASEÑA", cONTRASEÑA) :
                new ObjectParameter("CONTRASEÑA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOGINUSUARIO_Result>("LOGINUSUARIO", uSUARIOParameter, cONTRASEÑAParameter);
        }
    
        public virtual ObjectResult<PREGUNTABYID_Result> PREGUNTABYID(Nullable<int> iD_PREGUNTA)
        {
            var iD_PREGUNTAParameter = iD_PREGUNTA.HasValue ?
                new ObjectParameter("ID_PREGUNTA", iD_PREGUNTA) :
                new ObjectParameter("ID_PREGUNTA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PREGUNTABYID_Result>("PREGUNTABYID", iD_PREGUNTAParameter);
        }
    
        public virtual ObjectResult<PREGUNTASBYUSER_Result> PREGUNTASBYUSER(Nullable<int> iD_USUARIO)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PREGUNTASBYUSER_Result>("PREGUNTASBYUSER", iD_USUARIOParameter);
        }
    
        public virtual ObjectResult<USUARIOEXISTE_Result> USUARIOEXISTE(string uSUARIO)
        {
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USUARIOEXISTE_Result>("USUARIOEXISTE", uSUARIOParameter);
        }
    }
}
